apiVersion: v1
kind: Service
metadata:
  name: {{ include "mzinga-lab3.fullname" . }}-email-worker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mzinga-lab3.labels" . | nindent 4 }}
    app.kubernetes.io/component: email-worker
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: email-worker
  ports:
    - name: metrics
      port: {{ .Values.emailWorker.service.prometheusPort }}
      targetPort: metrics

