apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mzinga-lab3.fullname" . }}-worker-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mzinga-lab3.labels" . | nindent 4 }}
type: Opaque
stringData:
  mzinga-email: {{ required "emailWorker.credentials.email is required" .Values.emailWorker.credentials.email | quote }}
  mzinga-password: {{ required "emailWorker.credentials.password is required" .Values.emailWorker.credentials.password | quote }}

