mzingaApps:
  image:
    repository: mzinga-apps
    tag: "local"
    pullPolicy: Never
  replicaCount: 1
  service:
    port: 3000
  env:
    tenantId: "mzinga"
    environment: "prod"
    payloadSecret: "change-me-for-production"
    corsConfigs: "*"
    communicationsExternalWorker: "true"
    hooksUrlCommunicationsAfterChange: ""
    publicServerUrl: "http://localhost:3000"
    jsonLimitsSize: "20mb"
    disableTracing: "0"
    otelConsoleExporter: "1"
    enableZitadelPlugin: "0"

emailWorker:
  mode: "polling"
  image:
    repository: lab3-email-worker
    tag: "1.0.0"
    pullPolicy: Never
  replicaCount: 1
  service:
    prometheusPort: 8000
  credentials:
    email: ""
    password: ""
  env:
    pollIntervalSeconds: "5"
    emailFrom: "worker@mzinga.io"
    otlpServiceName: "email-worker"
    smtpHost: ""
    smtpPort: "1025"
    rabbitmqUrl: ""
    routingKey: "HOOKSURL_COMMUNICATIONS_AFTERCHANGE"
    exchangeName: "mzinga_events_durable"
    queueName: "communications-email-worker"

rabbitmq:
  enabled: false
  image:
    repository: rabbitmq
    tag: "3-management"
    pullPolicy: IfNotPresent
  waitImage:
    repository: busybox
    tag: "1.36"
    pullPolicy: IfNotPresent
  service:
    amqpPort: 5672
    managementPort: 15672
  auth:
    username: "guest"
    password: "guest"

jaeger:
  image:
    repository: jaegertracing/all-in-one
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    uiPort: 16686
    otlpGrpcPort: 4317
    otlpHttpPort: 4318

mailhog:
  enabled: true
  image:
    repository: mailhog/mailhog
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    smtpPort: 1025
    uiPort: 8025

mongodb:
  auth:
    enabled: false
  persistence:
    enabled: false
